### ISSUE TITLE
Fatal error after activating "partial entries addon"

### ISSUE THREAD

**Issue by bluantinoo** [ethanclevenger91/gravity-forms-payment-continue#3]
Hello,
I've been using this little nice plugin for a while without any trouble.
But after I've installed and activated the "[partial entries addon](https://www.gravityforms.com/add-ons/partial-entries/)" (official addon) I get fatal errors.

```
PHP Notice:  Undefined index: payment_status in /app/public/wp-content/plugins/gf-payment-continue/gravity-forms-payment-continue.php on line 206
[09-Apr-2019 13:02:21 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /app/public/wp-content/plugins/gravityforms/forms_model.php:1440
Stack trace:
#0 /app/public/wp-content/plugins/gravityforms/includes/api.php(1318): GFFormsModel::update_entry_property(NULL, 'payment_status', 'Processing')
#1 /app/public/wp-content/plugins/gravityformspaypal/class-gf-paypal.php(567): GFAPI::update_entry_property(NULL, 'payment_status', 'Processing')
#2 /app/public/wp-content/plugins/gf-payment-continue/gravity-forms-payment-continue.php(426): GFPayPal->redirect_url(Array, Array, Array, Array)
#3 /app/public/wp-content/plugins/gf-payment-continue/gravity-forms-payment-continue.php(251): GravityFormsPaymentContinue->get_payment_url(Array, Array)
#4 /app/public/wp-content/plugins/gravityformspartialentries/class-gf-partial-entries.php(625): GravityFormsPaymentContinue->update_payment_url_meta('payment_url', Array, Array)
#5 /app/public/wp-content/plugins/gravityformspartialentries/class-gf-partial-entries.php(397): GF_Partial_Entries in /app/public/wp-content/plugins/gravityforms/forms_model.php on line 1440
[09-Apr-2019 13:03:01 UTC] PHP Warning:  Invalid argument supplied for foreach() in /app/public/wp-admin/includes/plugin.php on line 1560
[09-Apr-2019 13:03:01 UTC] PHP Notice:  Undefined index: payment_status in /app/public/wp-content/plugins/gf-payment-continue/gravity-forms-payment-continue.php on line 206
[09-Apr-2019 13:03:01 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /app/public/wp-content/plugins/gravityforms/forms_model.php:1440
Stack trace:
#0 /app/public/wp-content/plugins/gravityforms/includes/api.php(1318): GFFormsModel::update_entry_property(NULL, 'payment_status', 'Processing')
#1 /app/public/wp-content/plugins/gravityformspaypal/class-gf-paypal.php(567): GFAPI::update_entry_property(NULL, 'payment_status', 'Processing')
#2 /app/public/wp-content/plugins/gf-payment-continue/gravity-forms-payment-continue.php(426): GFPayPal->redirect_url(Array, Array, Array, Array)
#3 /app/public/wp-content/plugins/gf-payment-continue/gravity-forms-payment-continue.php(251): GravityFormsPaymentContinue->get_payment_url(Array, Array)
#4 /app/public/wp-content/plugins/gravityformspartialentries/class-gf-partial-entries.php(625): GravityFormsPaymentContinue->update_payment_url_meta('payment_url', Array, Array)
#5 /app/public/wp-content/plugins/gravityformspartialentries/class-gf-partial-entries.php(397): GF_Partial_Entries in /app/public/wp-content/plugins/gravityforms/forms_model.php on line 1440
[09-Apr-2019 13:05:02 UTC] PHP Warning:  Invalid argument supplied for foreach() in /app/public/wp-admin/includes/plugin.php on line 1560
```

Maybe because the payment status is not set when the form is still not fully submitted?

PS: Partial Entries works great if I deactivate Payment continue, and viceversa

**Comment by bluantinoo** [comment]
Don't know if [this](https://github.com/bluantinoo/gravity-forms-payment-continue/commit/46e2ee1e063adf2fdde30e2c1e1ecae69adb221e) is the best way, but on my setup, it has fixed the issue

**Comment by ethanclevenger91** [comment]
Huh, thanks for the heads up. I'll dig into that a bit. The fatal errors are from the other plugin, but could be stemming from notices in mine.
